---
default_scopes: []
optional_scopes:
  - openid
  - account_manager_access
  - deanonymise_tokens
  - email
  - reporting_access
  - migrate_users
  - transition_checker
  - level0
  - level1
hidden_scopes:
  - openid
  - email
  - transition_checker
  - level0
  - level1
