---
default_scopes: []
optional_scopes:
  - openid
  - account_manager_access
  - deanonymise_tokens
  - email
  - reporting_access
  - transition_checker
  - level0
  - level1
hidden_scopes:
  - openid
  - email
  - transition_checker
  - level0
  - level1
jwt_attributes_and_scopes: {
  "transition_checker_state": ["transition_checker"]
}
