---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest
      username: ((docker_hub_username))
      password: ((docker_hub_authtoken))
resources:
  - name: git-main
    type: git
    icon: github-circle
    source:
      uri: https://github.com/alphagov/govuk-account-manager-prototype.git
      branch: main

  - name: govuk-slack
    type: slack-notification
    source:
      url: https://hooks.slack.com/((slack_webhook_url))

  - name:  git-main-gems-dockerfile
    icon: github-circle
    type: git
    source:
      uri: https://github.com/alphagov/govuk-account-manager-prototype.git
      branch: main
      paths:
        - concourse/Dockerfile
        - Gemfile*

  - name: every-day
    type: time
    source:
      interval: 24h

  - name: tests-image
    type: docker-image
    icon: docker
    source:
      repository: ((readonly_private_ecr_repo_url))
      tag: govuk-accounts-manager-tests-image

jobs:
  - name: update-pipeline
    plan:
      - get: git-main
        trigger: true
      - set_pipeline: govuk-account-manager-prototype
        file: git-main/concourse/pipeline.yml

  - name: build-tests-image
    serial: true
    build_log_retention:
      builds: 100
    plan:
      - get: every-day
        trigger: true
      - get: git-main-gems-dockerfile
        trigger: true
      - put: tests-image
        params:
          build: git-main-gems-dockerfile
          dockerfile: git-main-gems-dockerfile/concourse/Dockerfile
        on_failure:
          put: govuk-slack
          params:
            channel: '#govuk-accounts-tech'
            username: 'Concourse (GOV.UK Accounts)'
            icon_emoji: ':concourse:'
            silent: true
            text: |
              :kaboom:
              Test image build for the GOV.UK Account manager has failed
              Failed build: http://cd.gds-reliability.engineering/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

  - name: run-quality-checks
    serial: true
    plan:
      - get: tests-image
        passed:
          - build-tests-image
        trigger: true
      - get: git-main
        trigger: true
      - task: run-tests-task
        image: tests-image
        config:
          inputs:
            - name: git-main
          outputs:
            - name: committer-details
          platform: linux
          run:
            dir: git-main
            path: bash
            args:
              - -c
              - |
                set -eu
                service postgresql start
                su - postgres -c "psql -c \"alter user postgres with password 'password';\""
                service redis-server start
                export TEST_DATABASE_URL="postgres://postgres:password@localhost:5432/accounts"
                export RAILS_ENV=test
                bundle install
                bundle exec rails db:setup
                bundle exec rails db:migrate
                bundle exec rake
        on_failure:
          put: govuk-slack
          params:
            channel: '#govuk-accounts-tech'
            username: 'Concourse (GOV.UK Accounts)'
            icon_emoji: ':concourse:'
            silent: true
            text: |
              :kaboom:
              Quality checks for the GOV.UK Account manager have failed
              Failed build: http://cd.gds-reliability.engineering/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

  - name: deploy-app-staging
    serial: true
    plan:
      - get: git-main
        trigger: true
        passed: [run-quality-checks]
      - task: deploy-to-paas
        file: git-main/concourse/tasks/deploy-to-govuk-paas.yml
        params:
          CF_ORG: govuk-accounts
          CF_APP_NAME: govuk-account-manager
          CF_SPACE: staging
          CF_STARTUP_TIMEOUT: 15 # minutes
          APP_INSTANCES: 1
          WORKER_INSTANCES: 1
          CDN_DOMAIN: account.staging.publishing.service.gov.uk
          ENABLE_REGISTRATION: "true"
          REQUIRE_BASIC_AUTH: "true"
          BASIC_AUTH_USERNAME: ((basic-auth-username))
          BASIC_AUTH_PASSWORD: ((basic-auth-password))
          APP_DOMAIN: www.staging.publishing.service.gov.uk
          WEBSITE_ROOT: https://www.staging.publishing.service.gov.uk
          EMAIL_ALERT_API_BEARER_TOKEN: ((email-alert-api-bearer-token))
          PLEK_SERVICE_EMAIL_ALERT_API_URI: https://email-alert-api.staging.publishing.service.gov.uk
          NOTIFY_API_KEY: ((notify-api-key-staging))
          NOTIFY_TEMPLATE_ID: 6074fdc2-03b3-4bb6-83fe-31220779c13b
          NOTIFY_SMS_TEMPLATE_ID: 51f0410b-0367-4e24-bf4d-17019791b77d
          FEATURE_FLAG_MFA: enabled
          OIDC_SIGNING_KEY: ((oidc-signing-key-staging))
          OIDC_PEPPER: ((oidc-pepper-staging))
          SECRET_KEY_BASE: ((secret-key-base-staging))
          PASSWORD_PEPPER: ((password-pepper-staging))
          ZENDESK_CLIENT_USERNAME: ((zendesk-api-username))
          ZENDESK_CLIENT_TOKEN: ((zendesk-api-key))
          ZENDESK_GROUP_ID: 360005155059
        on_failure:
          put: govuk-slack
          params:
            channel: '#govuk-accounts-tech'
            username: 'Concourse (GOV.UK Accounts)'
            icon_emoji: ':concourse:'
            silent: true
            text: |
              :kaboom:
              Staging deployment for the GOV.UK Account manager has failed
              Failed build: http://cd.gds-reliability.engineering/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

  - name: smoke-test-staging
    serial: true
    plan:
      - get: git-main
        trigger: true
        passed: [deploy-app-staging]
      - task: smoke-test
        file: git-main/concourse/tasks/smoke-test.yml
        timeout: 5m
        params:
          URL: 'https://((basic-auth-username)):((basic-auth-password))@www.account.staging.publishing.service.gov.uk'
          MESSAGE: "Checks that the application deployed to staging is not critically broken. If this fails, you should investigate immediately."
        on_failure:
          put: govuk-slack
          params:
            channel: '#govuk-accounts-tech'
            username: 'Concourse (GOV.UK Accounts)'
            icon_emoji: ':concourse:'
            silent: true
            text: |
              :kaboom:
              Staging smoke tests for the GOV.UK Account manager have failed
              Failed build: http://cd.gds-reliability.engineering/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

  - name: deploy-app-production
    serial: true
    plan:
      - get: git-main
        trigger: true
        passed: [smoke-test-staging]
      - task: deploy-to-paas
        file: git-main/concourse/tasks/deploy-to-govuk-paas.yml
        params:
          CF_ORG: govuk-accounts
          CF_APP_NAME: govuk-account-manager
          CF_SPACE: production
          CF_STARTUP_TIMEOUT: 15 # minutes
          APP_INSTANCES: 3
          WORKER_INSTANCES: 3
          CDN_DOMAIN: account.publishing.service.gov.uk
          ENABLE_REGISTRATION: "true"
          APP_DOMAIN: www.gov.uk
          WEBSITE_ROOT: https://www.gov.uk
          EMAIL_ALERT_API_BEARER_TOKEN: ((email-alert-api-bearer-token))
          PLEK_SERVICE_EMAIL_ALERT_API_URI: https://email-alert-api.publishing.service.gov.uk
          NOTIFY_API_KEY: ((notify-api-key-production))
          NOTIFY_TEMPLATE_ID: 6074fdc2-03b3-4bb6-83fe-31220779c13b
          NOTIFY_SMS_TEMPLATE_ID: 51f0410b-0367-4e24-bf4d-17019791b77d
          FEATURE_FLAG_MFA: enabled
          OIDC_SIGNING_KEY: ((oidc-signing-key-production))
          OIDC_PEPPER: ((oidc-pepper-production))
          SECRET_KEY_BASE: ((secret-key-base-production))
          PASSWORD_PEPPER: ((password-pepper-production))
          ZENDESK_CLIENT_USERNAME: ((zendesk-api-username))
          ZENDESK_CLIENT_TOKEN: ((zendesk-api-key))
          ZENDESK_GROUP_ID: 360005155059
        on_failure:
          put: govuk-slack
          params:
            channel: '#govuk-accounts-tech'
            username: 'Concourse (GOV.UK Accounts)'
            icon_emoji: ':concourse:'
            silent: true
            text: |
              :kaboom:
              Production deployment for the GOV.UK Account manager has failed
              Failed build: http://cd.gds-reliability.engineering/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

  - name: smoke-test-production
    serial: true
    plan:
      - get: git-main
        trigger: true
        passed: [deploy-app-production]
      - task: smoke-test
        file: git-main/concourse/tasks/smoke-test.yml
        timeout: 5m
        params:
          URL: 'https://((basic-auth-username)):((basic-auth-password))@www.account.publishing.service.gov.uk'
          MESSAGE: "Checks that the application deployed to production is not critically broken. If this fails, you should investigate immediately."
        on_failure:
          put: govuk-slack
          params:
            channel: '#govuk-accounts-tech'
            username: 'Concourse (GOV.UK Accounts)'
            icon_emoji: ':concourse:'
            silent: true
            text: |
              :kaboom:
              Production smoke tests for the GOV.UK Account manager have failed
              Failed build: http://cd.gds-reliability.engineering/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
