on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: accounts
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
      - uses: actions/cache@v1
        with:
          path: tmp/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - run: |
          bundle config path tmp/bundle
          bundle install --jobs 4 --retry 3

      - run: bundle exec rubocop

      - run: bundle exec brakeman

      - env:
          RAILS_ENV: test
          TEST_DATABASE_URL: "postgresql://postgres:postgres@localhost/accounts"
        run: |
          bundle exec rails db:setup
          bundle exec rake
